# Generated by Django 2.2.1 on 2019-05-20 13:21

from django.db import migrations, models
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('djnd', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clip',
            name='formats',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='djnd.TaggedFormatItem', to='djnd.FormatTag', verbose_name='Tags'),
        ),
        migrations.AlterField(
            model_name='clip',
            name='image',
            field=models.FileField(blank=True, upload_to='images/clip/'),
        ),
        migrations.AlterField(
            model_name='clip',
            name='languages',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='djnd.TaggedLanguageItem', to='djnd.LanguageTag', verbose_name='Tags'),
        ),
        migrations.AlterField(
            model_name='clip',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='djnd.TaggedGenericItem', to='djnd.GenericTag', verbose_name='Tags'),
        ),
        migrations.AlterField(
            model_name='clip',
            name='types',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='djnd.TaggedTypeItem', to='djnd.TypeTag', verbose_name='Tags'),
        ),
        migrations.AlterField(
            model_name='infopush',
            name='image',
            field=models.FileField(blank=True, upload_to='images/infopush/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.FileField(blank=True, upload_to='images/project/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='djnd.TaggedGenericItem', to='djnd.GenericTag', verbose_name='Tags'),
        ),
        migrations.AlterField(
            model_name='video',
            name='image',
            field=models.FileField(blank=True, upload_to='images/video/'),
        ),
        migrations.AlterField(
            model_name='video',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='djnd.TaggedGenericItem', to='djnd.GenericTag', verbose_name='Tags'),
        ),
    ]
