# Generated by Django 2.2.14 on 2021-05-11 11:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('djnd', '0003_auto_20191211_1452'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='infopush',
            options={'verbose_name': 'Info push', 'verbose_name_plural': 'Info pushes'},
        ),
        migrations.AddField(
            model_name='clip',
            name='alt',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='clip',
            name='desc',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='clip',
            name='url',
            field=models.URLField(blank=True, null=True, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='formattag',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='formattag',
            name='slug',
            field=models.SlugField(max_length=100, unique=True, verbose_name='slug'),
        ),
        migrations.AlterField(
            model_name='generictag',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='generictag',
            name='slug',
            field=models.SlugField(max_length=100, unique=True, verbose_name='slug'),
        ),
        migrations.AlterField(
            model_name='infopush',
            name='cta_text',
            field=models.CharField(max_length=512, verbose_name='Button text'),
        ),
        migrations.AlterField(
            model_name='infopush',
            name='cta_url',
            field=models.URLField(verbose_name='Button URL'),
        ),
        migrations.AlterField(
            model_name='infopush',
            name='desc',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='languagetag',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='languagetag',
            name='slug',
            field=models.SlugField(max_length=100, unique=True, verbose_name='slug'),
        ),
        migrations.AlterField(
            model_name='project',
            name='desc',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='project',
            name='url',
            field=models.URLField(blank=True, null=True, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='taggedformatitem',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='djnd_taggedformatitem_tagged_items', to='contenttypes.ContentType', verbose_name='content type'),
        ),
        migrations.AlterField(
            model_name='taggedformatitem',
            name='object_id',
            field=models.IntegerField(db_index=True, verbose_name='object ID'),
        ),
        migrations.AlterField(
            model_name='taggedgenericitem',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='djnd_taggedgenericitem_tagged_items', to='contenttypes.ContentType', verbose_name='content type'),
        ),
        migrations.AlterField(
            model_name='taggedgenericitem',
            name='object_id',
            field=models.IntegerField(db_index=True, verbose_name='object ID'),
        ),
        migrations.AlterField(
            model_name='taggedlanguageitem',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='djnd_taggedlanguageitem_tagged_items', to='contenttypes.ContentType', verbose_name='content type'),
        ),
        migrations.AlterField(
            model_name='taggedlanguageitem',
            name='object_id',
            field=models.IntegerField(db_index=True, verbose_name='object ID'),
        ),
        migrations.AlterField(
            model_name='taggedtypeitem',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='djnd_taggedtypeitem_tagged_items', to='contenttypes.ContentType', verbose_name='content type'),
        ),
        migrations.AlterField(
            model_name='taggedtypeitem',
            name='object_id',
            field=models.IntegerField(db_index=True, verbose_name='object ID'),
        ),
        migrations.AlterField(
            model_name='typetag',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='typetag',
            name='slug',
            field=models.SlugField(max_length=100, unique=True, verbose_name='slug'),
        ),
        migrations.AlterField(
            model_name='video',
            name='desc',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='video',
            name='url',
            field=models.URLField(blank=True, null=True, verbose_name='URL'),
        ),
    ]
