# Generated by Django 2.2.14 on 2021-05-11 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djnd', '0004_auto_20210511_1109'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='alt',
            field=models.TextField(blank=True, null=True),
        ),
    ]
