# Generated by Django 2.2.14 on 2021-05-11 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djnd', '0005_project_alt'),
    ]

    operations = [
        migrations.AddField(
            model_name='infopush',
            name='alt',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='alt',
            field=models.TextField(blank=True, null=True),
        ),
    ]
